// Curated Co-Op Games Database for Us
// Built with love, wit, and zero pressure!

const GAMES_DATA = [
  {
    id: "valheim",
    title: "Valheim",
    subtitle: "Viking Wilderness, Campfires & Norse Legends",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC & Xbox (Crossplay)",
    steamUrl: "https://store.steampowered.com/app/892970/Valheim/",
    trailerVideoId: "b8G9X5gqIeY", // Valheim official launch trailer
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/892970/header.jpg",
    vibeCategory: "building",
    vibeCategoryName: "🏰 Building & Creating",
    paceRating: "🌿 Relaxed Exploration",
    snackFriendliness: "☕ 8/10 — Lots of relaxing cooking & building time",
    beginnerFriendliness: "🌱 Friendly & intuitive — you move at your own speed",
    tags: ["Cozy Longhouses", "Sailing", "Crafting", "Open World", "Mythology"],
    pitch: "Imagine building a Nordic dream cabin by the water, listening to the rain on a wooden roof, cooking stews by the hearth, and sailing a boat into the sunset together. Total freedom to wander and explore.",
    plainSummary: "An atmospheric survival sandbox set in a mythical Viking world. There is no ticking clock—we can spend entire evenings just building a peaceful homestead, hunting deer, and exploring meadows.",
    thingsWeCanDo: [
      "Design and decorate a multi-story Viking wooden manor with hearths and rugs",
      "Tame wild boars and give them cute names around the farm",
      "Sail a boat across scenic oceans to discover mysterious uncharted islands",
      "Cook hearty honey stews, bake breads, and brew cozy potions",
      "Team up for epic boss battles whenever (and only if) we feel ready"
    ]
  },
  {
    id: "palworld",
    title: "Palworld",
    subtitle: "Cute Pals, Island Adventures & Automated Paradise",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC, Xbox & PS5",
    steamUrl: "https://store.steampowered.com/app/1623730/Palworld/",
    trailerVideoId: "E0tO3_a_oQY",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg",
    vibeCategory: "cozy",
    vibeCategoryName: "🛋️ Cozy & Relaxed",
    paceRating: "🌿 Casual & Rewarding",
    snackFriendliness: "🍿 9/10 — Your cute helpers do the heavy lifting",
    beginnerFriendliness: "🌟 Very approachable — like Pokémon meets Animal Crossing",
    tags: ["Cute Creatures", "Base Building", "Farming", "Open World", "Catch 'em All"],
    pitch: "It's Pokémon meets a cozy crafting resort. We can catch adorable magical creatures who voluntarily help water crops, generate electricity, and carry supplies while we ride giant birds across floating islands.",
    plainSummary: "A colorful open-world creature-collecting game. You explore a lush world, befriend cute critters called 'Pals', build a base, and let them help run the farm while exploring ancient ruins.",
    thingsWeCanDo: [
      "Catch dozens of adorable Pals of every element (fluffy sheep, fire foxes, flying dragons)",
      "Set up a sprawling ranch with hot springs, wheat farms, and cozy houses",
      "Ride flying or swimming Pals to explore secret hidden dungeons together",
      "Customize our characters with fun outfits and glide across scenic valleys",
      "Breed rare and ultra-cute Pals with unique traits"
    ]
  },
  {
    id: "aska",
    title: "ASKA",
    subtitle: "Viking Village Colony with Helpful AI Townsfolk",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC (Steam Early Access)",
    steamUrl: "https://store.steampowered.com/app/1898300/ASKA/",
    trailerVideoId: "e9L6s9YQ_Qk",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1898300/header.jpg",
    vibeCategory: "building",
    vibeCategoryName: "🏰 Building & Creating",
    paceRating: "🌿 Thoughtful Village Planning",
    snackFriendliness: "☕ 8/10 — AI villagers handle the manual labor",
    beginnerFriendliness: "🌱 Gentle pacing — you get to be the village chieftain",
    tags: ["Colony Sim", "Viking Settlement", "AI Helpers", "Survival", "Atmospheric"],
    pitch: "Ever wanted to run a lively Viking village where you summon NPC workers who happily chop wood, cook food, and farm for you? We get to design the layout, assign tasks, and watch our town come alive.",
    plainSummary: "A third-person Viking settlement builder. Unlike games where you have to do all the manual chopping yourself, here you invite villagers to your settlement to work for you while you plan the community.",
    thingsWeCanDo: [
      "Layout a scenic Nordic settlement with markets, workshops, and cozy huts",
      "Assign villagers to farming, fishing, or cooking and watch them carry out daily routines",
      "Go foraging for herbs, berries, and building materials in rich forests",
      "Defend the village walls alongside our loyal guard squads",
      "Survive seasonal changes and celebrate winter together in a warm longhouse"
    ]
  },
  {
    id: "no-mans-sky",
    title: "No Man's Sky",
    subtitle: "Infinite Relaxing Universe, Exotic Planets & Spaceships",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC, PS4/PS5, Xbox, Switch (Full Crossplay)",
    steamUrl: "https://store.steampowered.com/app/275850/No_Mans_Sky/",
    trailerVideoId: "D-uMFHoRR8w",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/275850/header.jpg",
    vibeCategory: "cozy",
    vibeCategoryName: "🛋️ Cozy & Relaxed",
    paceRating: "🧘 Pure Zen Exploration",
    snackFriendliness: "☕ 10/10 — Infinite pause, beautiful vistas, zero rush",
    beginnerFriendliness: "🌟 Extremely customizable — has a 'Relaxed' zero-danger mode",
    tags: ["Space Exploration", "Chill Vibes", "Planet Bases", "Creature Taming", "Gorgeous Visuals"],
    pitch: "Literally 18 quintillion planets to explore with zero loading screens. We can fly cool starships, build beach houses on tropical purple-grass alien worlds, and adopt glowing space butterflies as pets.",
    plainSummary: "An infinite universe exploration sandbox. It features stunning sci-fi colors, chill synth music, underwater base building, spaceship trading, and zero pressure—you can play on relaxed settings with no threat.",
    thingsWeCanDo: [
      "Fly spaceships seamlessly from space down to alien oceans and mountain peaks",
      "Build stunning glass-walled bases overlooking alien sunsets or deep oceans",
      "Feed and tame weird and adorable alien creatures (and ride them around)",
      "Customize our own starships, freighter capital ships, and astronaut suits",
      "Discover untouched paradise planets and name them after our inside jokes"
    ]
  },
  {
    id: "supermarket-together",
    title: "Supermarket Together",
    subtitle: "Chaotic Grocery Store Simulator & Cashier Comedy",
    status: "released",
    statusText: "Ready to Play Now (Free!)",
    releaseInfo: "Available Free on Steam (PC)",
    steamUrl: "https://store.steampowered.com/app/2710880/Supermarket_Together/",
    trailerVideoId: "r-9C5yM0Mfs",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2710880/header.jpg",
    vibeCategory: "chaos",
    vibeCategoryName: "🛒 Pure Fun & Chaos",
    paceRating: "⚡ Lively, Funny & Addictive",
    snackFriendliness: "🍿 9/10 — Pure silly retail therapy and laughs",
    beginnerFriendliness: "🌟 10/10 — Instant pickup & play for anyone",
    tags: ["Hilarious", "Store Management", "Cashier Sim", "Free to Play", "Casual Co-Op"],
    pitch: "We own a grocery store! One of us rings up crazy customers at the register, the other restocks cereal boxes, we order stock, set prices, chase down shoplifters with a broom, and expand our store empire.",
    plainSummary: "A hilarious, lightweight co-op supermarket sim. You unlock new product licenses, design store aisles, set prices (and decide whether to overcharge!), scan items, and keep the shelves stocked together.",
    thingsWeCanDo: [
      "Be the speedy cashier scanning barcodes and making change for quirky NPC shoppers",
      "Unbox deliveries and organize aisles with symmetrical aesthetic perfection",
      "Whack shoplifters attempting to sprint out the front door with stolen steaks",
      "Reinvest profits to buy expansion permits, freezers, and employee uniforms",
      "Decorate the store walls, change lighting, and hire helper staff"
    ]
  },
  {
    id: "helldivers-2",
    title: "Helldivers 2",
    subtitle: "Cinematic Sci-Fi Spectacle, Heroic Moments & Big Laughs",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC & PS5 (Crossplay)",
    steamUrl: "https://store.steampowered.com/app/553850/HELLDIVERS_2/",
    trailerVideoId: "l_OmsVp42h4",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/553850/header.jpg",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "🔥 High-Energy Action & Movie Moments",
    snackFriendliness: "🥤 6/10 — Fast-paced during 15-minute drops, chill on ship",
    beginnerFriendliness: "🎮 Easy difficulty sliders make it hilarious and forgiving",
    tags: ["Cinematic", "Sci-Fi Comedy", "Explosions", "Starship Troopers Vibe", "Co-Op Squad"],
    pitch: "Like starring in a hilarious, action-packed Hollywood sci-fi blockbuster together. We drop down in pods, call in dramatic laser strikes, and run away from goofy giant alien bugs while high-fiving.",
    plainSummary: "A blockbuster third-person shooter with over-the-top cinematic action and tongue-in-cheek satire. You team up to liberate planets, call down air supports and turrets, and extract on heroic shuttles.",
    thingsWeCanDo: [
      "Wear matching armored capes and emote high-five or hug on our spaceship bridge",
      "Call down laser orbital strikes, mech suits, and automatic sentry guns to do the work",
      "Fly across alien dunes with jump packs while laughing at chaotic explosions",
      "Play on lower, relaxed difficulty tiers for pure fun and visual eye-candy",
      "Celebrate cinematic last-second extractions while the heroic orchestral music swells"
    ]
  },
  {
    id: "subnautica-2",
    title: "Subnautica 2",
    subtitle: "Alien Ocean Wonder, Base Building & Submarines",
    status: "upcoming",
    statusText: "Upcoming Hype (In Development)",
    releaseInfo: "Announced for PC & Consoles (Multiplayer Co-Op!)",
    steamUrl: "https://store.steampowered.com/app/1962700/Subnautica_2/",
    trailerVideoId: "a9k5dE_9fG8",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1962700/header.jpg",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "🌿 Wonder & Exploration",
    snackFriendliness: "☕ 8/10 — Relax in your underwater glass observation room",
    beginnerFriendliness: "🌱 Wonderful pacing with customizable difficulty",
    tags: ["Underwater World", "Submarines", "Base Building", "Alien Oceans", "Exploration"],
    pitch: "The legendary underwater exploration game is finally adding co-op! We get to build underwater glass domes together, pilot submarines through bioluminescent reefs, and meet majestic alien sea creatures.",
    plainSummary: "An alien ocean adventure where players crash on an uncharted water world. Together, you dive through stunning coral ecosystems, craft diving gear, construct underwater sanctuaries, and uncover deep-sea secrets.",
    thingsWeCanDo: [
      "Construct a dream underwater research sanctuary with panoramic glass aquariums",
      "Co-pilot a multi-person submarine and honk the submarine horn in the deep",
      "Scan and catalog glowing alien fish, sea turtles, and plant life",
      "Craft high-tech swimming flippers, seamoths, and underwater habitat gardens",
      "Enjoy breathtaking bioluminescent light shows from the safety of our lounge"
    ]
  },
  {
    id: "chrono-odyssey",
    title: "Chrono Odyssey",
    subtitle: "Next-Gen Visual Masterpiece & Time-Bending Fantasy",
    status: "upcoming",
    statusText: "Upcoming Hype",
    releaseInfo: "Coming to PC, PS5 & Xbox Series X|S",
    steamUrl: "https://store.steampowered.com/app/2849880/Chrono_Odyssey/",
    trailerVideoId: "XU2HjAkn11g",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2849880/header.jpg",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "✨ Epic Cinematic World",
    snackFriendliness: "🍿 7/10 — Stunning vistas to pause and admire",
    beginnerFriendliness: "🎮 Modern accessible MMORPG systems with gorgeous guidance",
    tags: ["Unreal Engine 5", "Breathtaking Visuals", "Time Manipulation", "Fantasy", "Open World"],
    pitch: "One of the visually prettiest fantasy games ever made (Unreal Engine 5). You can manipulate time to pause or rewind the environment while exploring majestic castles, enchanted forests, and soaring skies.",
    plainSummary: "A next-generation open-world fantasy action RPG with jaw-dropping graphics. Players wield the Chronotector to manipulate time and explore a rich, living fantasy world filled with secrets and world events.",
    thingsWeCanDo: [
      "Explore breathtaking castle cities, snowy mountain peaks, and sunlit valleys",
      "Use time-manipulation abilities to rewind moments or freeze the environment",
      "Customize our characters with high-fashion fantasy armor, robes, and hairstyles",
      "Participate in massive cinematic world events and festival quests together",
      "Take gorgeous in-game scenic photos with photo mode"
    ]
  },
  {
    id: "slay-the-spire-2",
    title: "Slay the Spire 2",
    subtitle: "Smart, Cozy, Turn-Based Strategy (Now with Co-Op!)",
    status: "upcoming",
    statusText: "Upcoming Hype (2025/2026)",
    releaseInfo: "Coming to Steam (Early Access)",
    steamUrl: "https://store.steampowered.com/app/2868840/Slay_the_Spire_2/",
    trailerVideoId: "kUqWwO2r6l8",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2868840/header.jpg",
    vibeCategory: "puzzles",
    vibeCategoryName: "🧩 Puzzles & Big Brain",
    paceRating: "🧘 100% Turn-Based & Relaxed",
    snackFriendliness: "☕ 10/10 — Infinite time to think, talk, and sip tea",
    beginnerFriendliness: "🌟 Easy to understand — play cards, talk through combos",
    tags: ["Deckbuilder", "Turn Based", "Strategy", "Cozy Brain", "Zero Reflexes Needed"],
    pitch: "Zero reflexes required! It's purely turn-based like a board game. We look at our cards, discuss clever combos together over coffee, and create overpowered synergy combos at our own pace.",
    plainSummary: "The sequel to the most acclaimed deck-building game in history, now featuring multiplayer. You choose characters with unique decks, draft new powers, find quirky relics, and climb a mysterious spire.",
    thingsWeCanDo: [
      "Take all the time in the world on every turn—no countdown timers or stress",
      "Combine card powers to protect each other and unleash massive combo attacks",
      "Draft wacky magical artifacts and potions from quirky merchant shops",
      "Discuss strategies, test different hero classes, and laugh when a weird plan works",
      "Enjoy crisp, charming animated art and music while relaxing on the couch"
    ]
  },
  {
    id: "bellwright",
    title: "Bellwright",
    subtitle: "Build a Medieval Settlement & Lead a Community",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC (Steam Early Access)",
    steamUrl: "https://store.steampowered.com/app/1812450/Bellwright/",
    trailerVideoId: "g4oI9b8iZrk",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1812450/header.jpg",
    vibeCategory: "building",
    vibeCategoryName: "🏰 Building & Creating",
    paceRating: "🌿 Thoughtful World Building",
    snackFriendliness: "☕ 8/10 — Townspeople run production lines automatically",
    beginnerFriendliness: "🌱 Rich in-game guides and cooperative sharing",
    tags: ["Medieval", "Town Management", "Crafting", "Open World", "Community Building"],
    pitch: "Start with a humble campfire in a medieval forest, recruit wandering villagers, and gradually establish a thriving town with bakeries, weaver huts, blacksmiths, and stone houses.",
    plainSummary: "A medieval settlement builder and RPG. You establish towns, liberate oppressed peasants, assign jobs to villagers to craft goods and harvest crops, and explore a handcrafted historical world.",
    thingsWeCanDo: [
      "Place buildings, farm plots, windmills, and roads to design a flourishing village",
      "Recruit villagers with unique personalities, traits, and skills to join our town",
      "Harvest flax, brew herbal teas, tailor clothes, and manage the food stores",
      "Travel the scenic countryside on horseback to trade with neighboring towns",
      "Equip and train a village defense guard to protect our community"
    ]
  },
  {
    id: "we-were-here-tomorrow",
    title: "We Were Here Series",
    subtitle: "Walkie-Talkie Escape Room Puzzles Built for Two",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC, PlayStation & Xbox (Series includes multiple chapters)",
    steamUrl: "https://store.steampowered.com/app/865360/We_Were_Here_Together/",
    trailerVideoId: "i-LgqO_p6f4",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/865360/header.jpg",
    vibeCategory: "puzzles",
    vibeCategoryName: "🧩 Puzzles & Big Brain",
    paceRating: "🧩 Curious Mystery & Brain Teasers",
    snackFriendliness: "☕ 9/10 — Talk through clues at your own speed",
    beginnerFriendliness: "🌟 Intuitive: If you can describe what you see, you can win!",
    tags: ["Escape Room", "Pure Co-Op", "Walkie Talkie", "Mysteries", "Teamwork"],
    pitch: "The ultimate duo communication game. We are in separate rooms with only a walkie-talkie. I describe the weird symbols on my wall, you describe the puzzle machine in your room, and we crack the clues together!",
    plainSummary: "A series of cooperative escape-room puzzle adventures set in mysterious castle ruins. Success doesn't rely on fast reflexes—it's 100% about talking, listening, and sharing eureka moments.",
    thingsWeCanDo: [
      "Use our in-game walkie-talkies ('Roger that!') to describe mysterious clues to each other",
      "Solve clever visual riddles, secret code wheels, and enchanted lever mechanisms",
      "Explore antique libraries, alchemy laboratories, and snowy mountain passages",
      "Laugh at each other's ridiculous descriptions of geometric symbols",
      "Celebrate that sweet 'AHA!' moment when a puzzle clicks into place"
    ]
  },
  {
    id: "we-were-here-forever",
    title: "We Were Here Forever",
    subtitle: "The Grandest Mystery Adventure in Castle Rock",
    status: "released",
    statusText: "Ready to Play Now",
    releaseInfo: "Available on PC, PS4/PS5, Xbox One/Series X|S",
    steamUrl: "https://store.steampowered.com/app/1341290/We_Were_Here_Forever/",
    trailerVideoId: "d6q4v_a9T5Q",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1341290/header.jpg",
    vibeCategory: "puzzles",
    vibeCategoryName: "🧩 Puzzles & Big Brain",
    paceRating: "🧩 Immersive Duo Escape Adventure",
    snackFriendliness: "☕ 9/10 — Relaxed puzzle solving and exploration",
    beginnerFriendliness: "🌟 No combat or shooting—purely cooperative thinking",
    tags: ["Atmospheric", "Deep Mystery", "Walkie Talkie", "Grand Puzzles", "Story Driven"],
    pitch: "The biggest, most cinematic game in the We Were Here saga. Gorgeous fantasy environments, deeper lore, and puzzles that make us feel like an unstoppable genius detective duo.",
    plainSummary: "An expansive two-player puzzle adventure set in the surreal depths of Castle Rock. You must escape through forgotten dungeons, sunken catacombs, and a magical amusement park by communicating.",
    thingsWeCanDo: [
      "Navigate surreal steampunk machinery, sunken cathedrals, and carnival illusions",
      "Piece together centuries-old royal mysteries and ghostly stories",
      "Guide each other through labyrinthine mazes using maps and voice clues",
      "Take screenshots and compare notes to decode cryptic royal languages",
      "Experience a complete co-op journey with multiple endings"
    ]
  },
  {
    id: "windrose",
    title: "Windrose",
    subtitle: "Pirate Adventure, Island Exploration & High Seas Sailing",
    status: "released",
    statusText: "Available in Early Access / Development",
    releaseInfo: "Available on Steam (PC)",
    steamUrl: "https://store.steampowered.com/app/2485550/Windrose/",
    trailerVideoId: "74K4Yl26B4g",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2485550/header.jpg",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "🌿 Open Sea Exploration",
    snackFriendliness: "☕ 8/10 — Relax on the deck while sailing with the breeze",
    beginnerFriendliness: "🌱 Intuitive controls and fun nautical freedom",
    tags: ["Pirates", "Sailing", "Treasure Hunting", "Island Base", "PvE Adventure"],
    pitch: "Ever wanted to captain a pirate ship together? Catch the wind in the sails, discover secret tropical islands, dig up buried treasure chests, and build a coastal pirate hideaway.",
    plainSummary: "A PvE pirate survival adventure set in an alternative Age of Sail. You command a vessel, navigate winds, explore lush islands, craft gear, and fight mythical sea bosses with friends.",
    thingsWeCanDo: [
      "Steer our custom pirate ship while navigating ocean waves and weather",
      "Search uncharted tropical coves for hidden treasure maps and ancient loot",
      "Build a pirate sanctuary on a private tropical beach with docks and workshops",
      "Engage in thrilling naval cannon battles against rogue skeleton ships",
      "Play shanties and customize our pirate hats and outfits"
    ]
  },
  {
    id: "guild-wars-3",
    title: "Guild Wars 3",
    subtitle: "Next-Gen Online Fantasy Universe & Endless Adventure",
    status: "upcoming",
    statusText: "Upcoming Hype (In Development)",
    releaseInfo: "Announced in development by ArenaNet / NCSoft",
    steamUrl: "https://www.guildwars2.com/",
    trailerVideoId: "oXbH32v1t-A",
    bannerImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "✨ Rich Living Fantasy World",
    snackFriendliness: "🍿 8/10 — Explore beautiful cities and landscapes at your own pace",
    beginnerFriendliness: "🌟 Guild Wars is renowned for zero grinding and ultra player-friendly design",
    tags: ["Next-Gen MMO", "Fantasy", "Rich Lore", "Co-Op Story", "Exploration"],
    pitch: "The Guild Wars series is famous for being the most respectful of your time: zero forced grinding, super friendly cooperative community, gorgeous fantasy landscapes, and story you can play together.",
    plainSummary: "The newly confirmed next installment in the beloved Guild Wars franchise. Built for cooperative adventuring with dynamic world events, accessible gameplay, and deep character customization.",
    thingsWeCanDo: [
      "Create custom fantasy heroes (elemental mages, nature rangers, noble guardians)",
      "Explore soaring fantasy metropolises, enchanted glades, and hidden caverns",
      "Jump into spontaneous dynamic world events with other friendly players",
      "Collect stylish fashion, glowing mounts, and adorable companion pets",
      "Experience an epic co-op story campaign together without stressful gear treadmills"
    ]
  },
  {
    id: "darkswarm",
    title: "Darkswarm",
    subtitle: "Tactical Top-Down Sci-Fi Action & Procedural Infiltration",
    status: "upcoming",
    statusText: "Upcoming Hype",
    releaseInfo: "Coming to PC (Steam)",
    steamUrl: "https://store.steampowered.com/app/2303200/Darkswarm/",
    trailerVideoId: "P_zD393mZJc",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2303200/header.jpg",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "⚡ Tactical Team Play",
    snackFriendliness: "🥤 7/10 — Mission-based with clear pause points between ops",
    beginnerFriendliness: "🎮 Top-down view is easy to see everything and stay together",
    tags: ["Top-Down Shooter", "Sci-Fi", "Tactical", "Class Synergies", "Procedural Missions"],
    pitch: "A stylish top-down tactical sci-fi game where we pick specialized classes, deploy turrets and shields, and work as a coordinated strike team to tackle missions.",
    plainSummary: "A cooperative top-down tactical action shooter. Players explore dark alien-infested research complexes, utilizing class-based gadgets, hacking, and environmental hazards to accomplish objectives.",
    thingsWeCanDo: [
      "Choose complementary roles (Support, Tech Hacker, Heavy Shield, Recon Scout)",
      "Deploy automated defense sentries and healing drones for easy team support",
      "Hack security terminals and vent doors to outsmart alien hordes",
      "Upgrade weapons and unlock high-tech tactical suits after successful runs",
      "Enjoy crisp, top-down isometric visuals where you never lose sight of your partner"
    ]
  },
  {
    id: "aliens-fireteam-elite-2",
    title: "Aliens: Fireteam Elite 2",
    subtitle: "Iconic Sci-Fi Action, Bug Hunts & High-Tech Firepower",
    status: "upcoming",
    statusText: "Upcoming Hype",
    releaseInfo: "In Development for PC & Consoles",
    steamUrl: "https://store.steampowered.com/app/1549970/Aliens_Fireteam_Elite/",
    trailerVideoId: "g4oI9b8iZrk",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1549970/header.jpg",
    vibeCategory: "adventure",
    vibeCategoryName: "⚔️ Epic Adventures & Sci-Fi",
    paceRating: "🔥 Action-Packed Sci-Fi Thrills",
    snackFriendliness: "🥤 6/10 — Short thrilling missions, perfect for an evening session",
    beginnerFriendliness: "🎮 Easy difficulty modes with automated combat drones",
    tags: ["Alien Universe", "Co-Op Shooter", "Sci-Fi Action", "Tech Classes", "Movie Atmosphere"],
    pitch: "Step into the iconic movie universe! We gear up with smart guns (which auto-aim for you!), place electric fences, and cover each other's backs through eerie futuristic corridors.",
    plainSummary: "The upcoming sequel in the Aliens co-op franchise. Play as Colonial Marines navigating derelict spacecraft, alien hives, and research facilities with customizable loadouts and perk trees.",
    thingsWeCanDo: [
      "Use the iconic Smart Gun that automatically locks onto targets for effortless shooting",
      "Deploy Doc healing stations and Technician shock traps to control the battlefield",
      "Customize our marine with cool helmets, weapon skins, and armor decals",
      "Experience thrilling story campaigns with authentic movie sound effects and pulse rifles",
      "Laugh and celebrate narrow escapes as the elevator doors slam shut"
    ]
  },
  {
    id: "runescape-dragonwilds",
    title: "RuneScape: Dragonwilds",
    subtitle: "Cozy Fantasy World, Dragons, Skills & Magic",
    status: "upcoming",
    statusText: "Upcoming Hype",
    releaseInfo: "In development within the RuneScape Universe",
    steamUrl: "https://www.runescape.com/",
    trailerVideoId: "dQw4w9WgXcQ",
    bannerImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    vibeCategory: "cozy",
    vibeCategoryName: "🛋️ Cozy & Relaxed",
    paceRating: "🌿 Relaxing Skill Leveling & Quests",
    snackFriendliness: "☕ 10/10 — Perfect companion while chatting or watching a show",
    beginnerFriendliness: "🌟 Famous for chill, self-paced progression",
    tags: ["Fantasy RPG", "Cozy Skilling", "Dragon Lore", "Quests", "Relaxed Pace"],
    pitch: "The ultimate cozy fantasy playground. You can level up cooking, fishing, woodcutting, or magic, bake cakes, go on whimsical humorous quests, and explore charming medieval villages.",
    plainSummary: "A fantasy adventure rooted in the legendary RuneScape universe. Emphasizes self-directed progression where doing mundane cozy things (like baking pies or lighting campfires) is just as rewarding as slaying dragons.",
    thingsWeCanDo: [
      "Train cozy life-skills together: fishing by the lake, baking pies, weaving magic robes",
      "Embark on whimsical quests loaded with classic British humor and eccentric characters",
      "Tame and care for baby dragons and mythical pets",
      "Trade resources with each other to craft high-level gear and home decorations",
      "Hang out in lively fantasy taverns and listen to classic medieval tunes"
    ]
  },
  {
    id: "killing-floor-3",
    title: "Killing Floor 3",
    subtitle: "High-Octane Sci-Fi Defense & Late-Night Arcade Thrills",
    status: "upcoming",
    statusText: "Upcoming Hype (2025/2026)",
    releaseInfo: "Coming to PC, PS5 & Xbox Series X|S",
    steamUrl: "https://store.steampowered.com/app/1430190/Killing_Floor_3/",
    trailerVideoId: "V_Zg6U4d08A",
    bannerImage: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1430190/header.jpg",
    vibeCategory: "chaos",
    vibeCategoryName: "🛒 Pure Fun & Chaos",
    paceRating: "⚡ Arcade Horde Survival",
    snackFriendliness: "🍿 7/10 — 60-second trader breaks between every wave to rest",
    beginnerFriendliness: "🎮 Easy difficulty provides unlimited ammo and high health",
    tags: ["Horde Defense", "Sci-Fi Cyberpunk", "Over-the-Top Action", "Arcade Fun", "Upgrades"],
    pitch: "Pure arcade action fun! We hold down a sci-fi room, weld doors shut, lay down laser tripmines, and visit the holographic shop pod between waves to buy ridiculous futuristic laser weapons.",
    plainSummary: "A cooperative wave-based sci-fi survival shooter set in 2091. Teams of up to 6 players fight off waves of bio-engineered cybernetic creatures, upgrading weapons and perks at the trader between rounds.",
    thingsWeCanDo: [
      "Weld steel blast doors shut and lay freeze mines to create a safe zone",
      "Play as a field medic with healing dart guns to keep everyone topped up",
      "Unlock cyberpunk gadgets like drone swarms and electric gravity cannons",
      "Shop at the glowing neon weapon pods during tranquil intermission rounds",
      "Experience slow-motion 'Zed Time' where everything goes matrix-style cinematic"
    ]
  }
];
